name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: "1"

jobs:
  test:
    permissions: {}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }}, Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install tox
        run: uv tool install --with tox-uv tox

      - name: Run tests with PyTest 9
        run: tox
        env:
          TOXENV: ${{ matrix.python-version }}-pytest-9
          PYTEST_PLUGINS: pytest_github_actions_annotate_failures,rerunfailures,xdist

      - name: Run tests with PyTest 8
        run: tox
        env:
          TOXENV: ${{ matrix.python-version }}-pytest-8
          PYTEST_PLUGINS: pytest_github_actions_annotate_failures,rerunfailures,xdist

      - name: Run tests with PyTest 7
        run: tox
        if: runner.os != 'Windows'
        env:
          TOXENV: ${{ matrix.python-version }}-pytest-7
          PYTEST_PLUGINS: pytest_github_actions_annotate_failures,rerunfailures,xdist

  post-test:
    name: All tests passed
    if: always()
    needs: [test]
    permissions: {}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
